"""Study-level RAD-DINO image retrieval for the agentic pipeline."""

from medagentx.retrieval.constants import (
    CHROMA_DISTANCE_SPACE,
    DEFAULT_COLLECTION_NAME,
    DEFAULT_EMBED_BATCH_SIZE,
    DEFAULT_EMBED_NUM_WORKERS,
    DEFAULT_MAX_DOCUMENT_CHARS,
    DEFAULT_RETRIEVAL_SUBDIR,
    DEFAULT_TOP_K,
    EMBEDDING_BACKEND_ID,
    EXCLUDE_SAME_PATIENT,
    EXCLUDE_SAME_STUDY,
    INDEX_BUILD_SPLIT,
    INDEX_METADATA_COLUMNS,
    QUERY_CANDIDATE_MIN_EXTRA,
    QUERY_CANDIDATE_MULTIPLIER,
    REPORT_PAYLOAD_COLUMNS,
    RETRIEVAL_INDEX_ID,
    RETRIEVAL_POLICY_VERSION,
)
from medagentx.retrieval.documents import (
    build_retrieval_document,
    build_study_report_table,
    truncate_document,
)
from medagentx.retrieval.embed import (
    build_study_embedding_loader,
    collect_study_embeddings,
    extract_study_embeddings,
    load_embedding_model,
)
from medagentx.retrieval.index import (
    IndexedStudy,
    RetrievedStudy,
    build_index_records,
    chroma_document_id,
    clean_metadata_value,
    filter_retrieved_studies,
    get_chroma_collection,
    query_candidate_count,
    query_similar_studies,
    write_chroma_index,
    write_index_manifest,
)

__all__ = [
    "CHROMA_DISTANCE_SPACE",
    "DEFAULT_COLLECTION_NAME",
    "DEFAULT_EMBED_BATCH_SIZE",
    "DEFAULT_EMBED_NUM_WORKERS",
    "DEFAULT_MAX_DOCUMENT_CHARS",
    "DEFAULT_RETRIEVAL_SUBDIR",
    "DEFAULT_TOP_K",
    "EMBEDDING_BACKEND_ID",
    "EXCLUDE_SAME_PATIENT",
    "EXCLUDE_SAME_STUDY",
    "INDEX_BUILD_SPLIT",
    "INDEX_METADATA_COLUMNS",
    "IndexedStudy",
    "QUERY_CANDIDATE_MIN_EXTRA",
    "QUERY_CANDIDATE_MULTIPLIER",
    "REPORT_PAYLOAD_COLUMNS",
    "RETRIEVAL_INDEX_ID",
    "RETRIEVAL_POLICY_VERSION",
    "RetrievedStudy",
    "build_index_records",
    "build_retrieval_document",
    "build_study_embedding_loader",
    "build_study_report_table",
    "chroma_document_id",
    "clean_metadata_value",
    "collect_study_embeddings",
    "extract_study_embeddings",
    "filter_retrieved_studies",
    "get_chroma_collection",
    "load_embedding_model",
    "query_candidate_count",
    "query_similar_studies",
    "truncate_document",
    "write_chroma_index",
    "write_index_manifest",
]
